"""environment parameters"""
options = {
    'alfanumremoval': True,
    'dotdashsplits': True,
    'lowerstring': True,
    'nfd': True,
    'singleletterremoval': True,
    'specialremoval': True,
    'stripstring': True,
    'descColumn': "MAKTX",
    'normColumn': "normalizedMAKTX",
    'normColumnNoBrands': "normalizedMAKTX_2",
    'langColumn': "langDetected",
    'transColumn': "translated",
    'langDetThreshold': 0.8,

    'ngramLength': 4,
    'numHashTables': 5,
    'simThreshold': 0.1,

    'inputDataFile': "../alex/output/campofrio_table/",
    'brandsFile': "../alex/data/fabricantes.txt",
    'langDetModelFile': "jslmodels/langdetection-models/ld_wiki_tatoeba_cnn_375_xx_2.7.0_2.4_1607184873730",

    'sentDetectModelFile': "jslmodels/sentencedetection/sentence_detector_dl_xx_2.7.0_2.4_1609610616998",
    'langTransModelFile': "jslmodels/langtranslation/opus_mt_mul_en_xx_3.1.0_2.4_1622554306551"
}

# columnas relevantes del dataset (plataforma):
dict_cols_stratio = {
    'row_id': 'row_id',
    '_source--ERNAM[created_by]': 'ERNAM',
    '_source--E1MARCM[Plants]--WERKS[Plant]': 'WERKS',
    '_source--MAKTX[material_description]': 'MAKTX',
    '_source--MATNR[material_id]': 'MATNR',
    '_source--MATNR_ISO[material_id_by_language]': 'MATNR_ISO',
    '_source--SPRAS_ISO[language]': 'SPRAS_ISO',
    '_source--MATKL[material_group]': 'MATKL',
    '_source--ZMANUFACTURER[manufacturer]': 'ZMANUFACTURER',
    '_source--ZMANUF_REF[manufacturer_ref]': 'ZMANUF_REF',
    '_source--LVORM[df_at_client_level]': 'LVORM',
    '_source--MSTAE[x_plant_matl_status]': 'MSTAE'
}

dict_cols_local = {
    'row_id': 'row_id',
    'ERNAM': 'ERNAM',
    'E1MARCM[Plants]--WERKS[Plant]': 'WERKS',
    'MAKTX': 'MAKTX',
    'MATNR': 'MATNR',
    'MATNR_ISO': 'MATNR_ISO',
    'SPRAS_ISO': 'SPRAS_ISO',
    'MATKL': 'MATKL',
    'ZMANUFACTURER': 'ZMANUFACTURER',
    'ZMANUF_REF': 'ZMANUF_REF',
    'MSTAE': 'MSTAE',
    'E1MVKEM[sales]--LVORM[df_at_client_level]': 'LVORM'}

brands = [
    "ab",
    "abb",
    "aignep",
    "alfa laval",
    "allan bradley",
    "allen bradley",
    "amphenol",
    "arandis",
    "armacell",
    "asgo",
    "astrosyn",
    "atlas copco",
    "attema",
    "atx",
    "autotherm",
    "aventics",
    "azura",
    "b&r",
    "bachmann",
    "balluff",
    "bando",
    "baumer",
    "baumeur",
    "beckhoff",
    "beckoff",
    "beijer",
    "beko",
    "berdo",
    "berner",
    "bikat",
    "bilwinco",
    "binder",
    "bizerba",
    "bobinadora jr",
    "boix",
    "bonfiglioli",
    "bosch",
    "breco",
    "burkert",
    "busch",
    "captemp_falex",
    "carometec",
    "cembre",
    "cfs",
    "chiorino",
    "circutor",
    "cognex",
    "colson",
    "coval",
    "crc",
    "danfoss",
    "deal ii",
    "deltasintra",
    "dexis",
    "digi",
    "dordal",
    "dosiper",
    "dreumex",
    "duker",
    "duracell",
    "eactech",
    "eao",
    "eaton",
    "eatonmoeller",
    "ebmpapst",
    "eldon",
    "elesa ganter",
    "eliwell",
    "elobau",
    "emile maurin",
    "endress&hauser",
    "eti",
    "euchner",
    "fag",
    "fam",
    "fanuc",
    "fenix",
    "fest8",
    "festo",
    "filp",
    "finder",
    "fluid force",
    "foss",
    "fox",
    "freund",
    "frincor",
    "frontmatec",
    "ft solutions",
    "fuchs",
    "fuchs lubricantes",
    "fuji electric co.",
    "full dip",
    "garos",
    "gates",
    "gea",
    "geacfs",
    "gedore",
    "generico",
    "ggm",
    "gh ulma",
    "graselli",
    "guelt",
    "habasit",
    "hagedorn",
    "handtmann",
    "hansen",
    "harting",
    "hengstler",
    "herion",
    "hiwin",
    "holac",
    "honsberg",
    "ide",
    "ifm",
    "igus",
    "iko",
    "ina",
    "indauto",
    "interflon",
    "interroll",
    "intralox",
    "ishida",
    "itoh denki",
    "karlklein",
    "knipex",
    "kollmorguen",
    "labycool",
    "laska",
    "legris",
    "lenze",
    "leuze",
    "lion",
    "maja",
    "maquicartaxo",
    "maquinaria industrial farres",
    "marel",
    "maurer-atmos",
    "maxon",
    "meca systeme",
    "mecanizados arribas",
    "mecanizados belvis",
    "mecanizados nozal",
    "mecaprec",
    "mennekes",
    "metalconser",
    "metalquimia",
    "mettler toledo",
    "mhs",
    "michaud",
    "minimotor",
    "misumi",
    "mitsubishi",
    "moeller",
    "mondini",
    "moreira",
    "moreira fc",
    "mosca",
    "multitec",
    "multivac",
    "multiwing",
    "murr elektronik",
    "mut",
    "mycom",
    "narviflex",
    "ninguno",
    "nozal",
    "omron",
    "optibelt",
    "panasonic",
    "parker",
    "partool",
    "paul",
    "pepperl+fuchs",
    "pferd",
    "phoenix",
    "phoenix contact",
    "pnumatis",
    "polyclip",
    "primedge",
    "pujolas",
    "radar",
    "rama",
    "ravenwood",
    "releco",
    "renold",
    "rexel",
    "rexroth",
    "risco",
    "rofled",
    "rose",
    "roser",
    "rotogal",
    "rustoleum",
    "rust-oleum",
    "sartorius",
    "sato",
    "saycalsa",
    "schmalz",
    "schmersal",
    "schneider",
    "sertec",
    "sew",
    "sew eurodrive",
    "seydelmann",
    "siba",
    "sick",
    "siemens",
    "sigmatek",
    "simia",
    "sinel",
    "skf",
    "skillpack",
    "smc",
    "snp",
    "sodeca",
    "sodicor",
    "soncini",
    "spirax sarco",
    "stanley",
    "stroter",
    "suez",
    "sunon",
    "takex",
    "tatasteel",
    "tavil",
    "te connectivity",
    "teco motovario",
    "tecsal",
    "telemecanique",
    "tesa",
    "thomas precision",
    "tipper tie",
    "toshiba",
    "trelleborg",
    "tsubaki",
    "turbocut",
    "turck",
    "ulma",
    "unex",
    "valco melton",
    "vemag",
    "victorinox",
    "viking",
    "vyc",
    "waircom",
    "wallther",
    "weber",
    "weg",
    "weidmuller",
    "wenglor",
    "witt",
    "wolfking",
    "xucla",
    "zemper",
    "zenner",
    "zeta",
    "zorpack",
    "tirolabel",
    "seeger",
    "asco",
    "megaslicer",
    "knecht",
    "gewiss",
    "pullzall",
    "elesa",
    "scanbelt",
    "mac",
    "macitex",
    "timken",
    "honeywell",
    "inotec ",
    "bernstein"
]